#!/bin/bash

FILENAME=$1

if [ ! -e "$FILENAME.aux" ]; then
       xelatex src/$FILENAME
fi

FINISHED=1

while [[ "$FINISHED" -eq 1 ]]; do
  mv $FILENAME.aux $FILENAME.aux.old
  xelatex src/$FILENAME
  FINISHED=$(cmp -s $FILENAME.aux $FILENAME.aux.old)
done

rm $FILENAME.aux.old
